In [3]:
import numpy as np

In [4]:
# numpy is numerical python 
# numerical powerful library for numerics and metric operations
# numerical array 

In [6]:
# creation of a numerical array
# creation from the list
arr=np.array([1,2,3]) # single dimensional array
print(arr)

[1 2 3]


In [7]:
arr.shape # col,row

(3,)

In [8]:
arr.ndim # dimension of the array

1

In [9]:
arr.dtype # data type (int)

dtype('int64')

In [11]:
# creatio of a multidimensional array
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [14]:
b.ndim # 2D

2

In [16]:
b.dtype

dtype('int64')

In [18]:
b.shape

(2, 3)

In [22]:
# 3D
c=np.array([[1,2,3],[2,3,4],[4,5,6]])
print(c)

[[1 2 3]
 [2 3 4]
 [4 5 6]]


In [24]:
c.dtype

dtype('int64')

In [26]:
c.ndim # dimension is 2 because eg.cube

2

In [28]:
c.shape

(3, 3)

In [30]:
c.size # no of elements

9

In [34]:
a3 = np.array([
    [[1,2],[1,3]],
    [[5,6],[6,7]]
    ])
print(a3)

[[[1 2]
  [1 3]]

 [[5 6]
  [6 7]]]


In [36]:
a3.ndim # 3d 

3

In [39]:
a3.shape # xyz cooordinates

(2, 2, 2)

In [41]:
a3.shape

(2, 2, 2)

In [43]:
a3.dtype

dtype('int64')

In [45]:
a3.size # elements

8

In [84]:
# built in 
#(2,3) matrix
z=np.zeros((2,2))
print(z)


[[0. 0.]
 [0. 0.]]


In [83]:
d = np.ones((2,3))
print(d)

[[1. 1. 1.]
 [1. 1. 1.]]


In [58]:
# arrange va;lues with difference 2 from 0 to 10
e=np.arange(0,10,2)
print(e)

[0 2 4 6 8]


In [61]:
f= np.arange(1,100,7)
f

array([ 1,  8, 15, 22, 29, 36, 43, 50, 57, 64, 71, 78, 85, 92, 99])

In [65]:
g=np.linspace(1,10,5)
g # starting to ending values with 5 difference in decimals

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [67]:
h=np.linspace(0,1,10) # equal different values betwwen 0 and 1 in equal distance
h

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [69]:
i=np.linspace(0,5,10)
i

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [72]:
# equal matrices or identity matrix
j=np.eye(3)
print(j)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [76]:
n= np.array([[1,2,3],[2,3,4]])
print(n)

[[1 2 3]
 [2 3 4]]


In [78]:
n.ndim

2

In [80]:
m=np.array([[1,2,3],[2,3,4],[3,4,5]])
print(m)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [82]:
o=np.array([
    [[1,2],[2,3]],
    [[2,3],[3,4]],
    [[4,5],[5,4]]
])
print(o)

[[[1 2]
  [2 3]]

 [[2 3]
  [3 4]]

 [[4 5]
  [5 4]]]


In [87]:
arr1 = np.array([1,2,4]) # 1 D
arr2=np.array([3,4,5])
print(arr1)
print(arr2)

[1 2 4]
[3 4 5]


In [89]:
arr1+arr2

array([4, 6, 9])

In [91]:
arr1*arr2

array([ 3,  8, 20])

In [93]:
arr1**2

array([ 1,  4, 16])

In [94]:
# matrix operation

In [97]:
p=np.dot(arr1,arr2) #1*3 + 2*4 + 4*5 #64 data type
p 

np.int64(31)

In [99]:
q=np.array([1,2,3],dtype=float)
print(q)

[1. 2. 3.]


In [104]:
q=np.array(["a","b","c"])
print(q)

['a' 'b' 'c']


In [106]:
q.dtype

dtype('<U1')

In [119]:
d2=np.array([[1,2,3],[3,4,5]])
d3=np.array([[10,12,13],[13,14,15]])
d2


array([[1, 2, 3],
       [3, 4, 5]])

In [120]:
d3

array([[10, 12, 13],
       [13, 14, 15]])

In [122]:
d2+d3

array([[11, 14, 16],
       [16, 18, 20]])

In [124]:
d2*d3

array([[10, 24, 39],
       [39, 56, 75]])

In [126]:
d2**3

array([[  1,   8,  27],
       [ 27,  64, 125]])

In [128]:
d3/d2

array([[10.        ,  6.        ,  4.33333333],
       [ 4.33333333,  3.5       ,  3.        ]])

In [144]:
np.dot(d2,d2)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [133]:
d3.ndim

2

In [135]:
d2.ndim

2

In [137]:
d3.shape

(2, 3)

In [139]:
d2.shape

(2, 3)

In [141]:
d3.size

6

In [143]:
d2.size

6

In [148]:
d3=d3.reshape(3,2) # colums to rows rows to columns (bcoz 2*3 can multiply 3*2)

In [149]:
np.dot(d2,d3)

array([[ 78,  83],
       [152, 163]])

In [151]:
d3

array([[10, 12],
       [13, 13],
       [14, 15]])

In [162]:
d2.reshape(2,3)
d2

array([[1, 2, 3],
       [3, 4, 5]])

In [156]:
d2

array([[1, 2, 3],
       [3, 4, 5]])

In [168]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [170]:
b.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [172]:
np.mean(b)

np.float64(3.5)

In [174]:
np.median(b)

np.float64(3.5)

In [177]:
np.std(b) # standard deviation

np.float64(1.707825127659933)

In [179]:
np.sin(b)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [181]:
np.cos(b)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [183]:
np.min(b)

np.int64(1)

In [185]:
b.max()

np.int64(6)

In [187]:
b.sum()

np.int64(21)

In [189]:
np.unique(b) # removes duplicates

array([1, 2, 3, 4, 5, 6])

In [191]:
np.sort(b)

array([[1, 2, 3],
       [4, 5, 6]])

In [193]:
np.concatenate([d2,b]) # combining arrays 

array([[1, 2, 3],
       [3, 4, 5],
       [1, 2, 3],
       [4, 5, 6]])

AttributeError: 'numpy.ndarray' object has no attribute 'mode'