In [2]:
import numpy as np

In [3]:
# creating 1D
arr1 = np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [4]:
# creating 2 D array 
arr2 = np.array([[1,2,3],[4,5,6]]) # 2D that is 2 one dimensional arrays
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
n2=np.zeros([3,3])
n2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
n3 = np.zeros([3,5],dtype='int32') # dtype to avoid floating poits
n3

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

In [7]:
n4= np.ones([2,3,3],dtype='int32')
n4

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int32)

In [8]:
empty= np.empty([1,3])
empty

array([[ 1.10312161e-311,  0.00000000e+000, -7.23926714e+077]])

In [9]:
n6 = np.arange(10)
n6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
n7=np.arange(-5,5,1) # start: stop :step
n7 

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [11]:
# linearly spaced entities 
n8=np.linspace(0,20,5, dtype='int32')
n8

array([ 0,  5, 10, 15, 20], dtype=int32)

In [12]:
# value filling
n9=np.full([2,5],99)
n9

array([[99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99]])

In [13]:
n10=np.full([3,3],True)
n10

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [14]:
n11=np.empty([3,3])
n11

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
n11.fill(99)
n11

array([[99., 99., 99.],
       [99., 99., 99.],
       [99., 99., 99.]])

In [16]:
print(n11[1])

[99. 99. 99.]


In [34]:
print(n11[:,0])

[99. 99. 99.]


In [35]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
print(arr2[:,0])

[1 4]


In [37]:
print(arr2[:,1])

[2 5]


In [39]:
print(arr2[:,2])

[3 6]


In [17]:
# accessing elements
# array elements starts from 0
print(arr2[1])

[4 5 6]


In [18]:
print(arr2[-1])

[4 5 6]


In [19]:
#2d
print(arr2[1][0])

4


In [20]:
print(arr2[1,2])

6


In [21]:
print(arr2[:,0]) # slicing # column elements 

[1 4]


In [22]:
print(arr2[:,2]) # collumn

[3 6]


In [23]:
a2=np.size(arr2)
print(a2)

6


In [24]:
arr3=np.ones([2,3,3],dtype='int32')
arr3

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int32)

In [25]:
arr3[1,1,2]=10 # replacing values
arr3

array([[[ 1,  1,  1],
        [ 1,  1,  1],
        [ 1,  1,  1]],

       [[ 1,  1,  1],
        [ 1,  1, 10],
        [ 1,  1,  1]]], dtype=int32)

In [26]:
arr4=np.array([
    [[1,2,4]],
    [[5,6,8]],
    [[9,10,11]]
])
arr4

array([[[ 1,  2,  4]],

       [[ 5,  6,  8]],

       [[ 9, 10, 11]]])

In [27]:
# size and shape

In [28]:
print(arr4.ndim)

3


In [29]:
print(arr4.shape) # dimension 

(3, 1, 3)


In [30]:
print(arr4.size) # number of elements

9


In [31]:
print(arr4.itemsize) # space of each items (each element size or memory need)

8


In [32]:
print(arr4.dtype)

int64


In [33]:
print(arr4.nbytes) #8*9=72

72


In [41]:
ar1=np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]]
])
ar1

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [42]:
print(ar1.shape)

(2, 3, 3)


In [45]:
ar1[0,1,2]=10
ar1

array([[[ 1,  2,  3],
        [ 4,  5, 10],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [46]:
print(ar1[0][2][2])

9


In [47]:
print(ar1[0][:,2])

[ 3 10  9]


In [48]:
print(ar1[1][:,1])

[11 14 17]


In [49]:
print(ar1[0][0])

[1 2 3]


In [54]:
print(ar1[:,2]) # in all blocks 2nd row

[[ 7  8  9]
 [16 17 18]]


In [55]:
print(ar1[:,:,2]) # all the columns in all blocks first : specifies all the bloacks 2: specifies all the columns

[[ 3 10  9]
 [12 15 18]]


In [56]:
print(ar1.size)

18


In [57]:
print(ar1.shape)

(2, 3, 3)


In [59]:
ar1[1,2,2]=10
ar1

array([[[ 1,  2,  3],
        [ 4,  5, 10],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 10]]])

In [60]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
arr2[1,1]=10
arr2

array([[ 1,  2,  3],
       [ 4, 10,  6]])

In [63]:
ar1.ndim

3

In [64]:
ar1.dtype

dtype('int64')

In [65]:
ar1.itemsize

8

In [67]:
ar1.nbytes # 18 * 8

144

In [68]:
ar1.size

18

In [70]:
n10=([2,3,4,5,6,7,1])
n10.sort()
n10

[1, 2, 3, 4, 5, 6, 7]

In [76]:
np.sort(arr2) # row wise sorting

array([[ 1,  2,  3],
       [ 4,  6, 10]])

In [78]:
np.sort(arr2,axis=0) # column wise sorting

array([[ 1,  2,  3],
       [ 4,  6, 10]])

In [79]:
np.sort(arr2,axis=1) # row wise  # default axis is -1 last axis 

array([[ 1,  2,  3],
       [ 4,  6, 10]])

In [73]:
ar1

array([[[ 1,  2,  3],
        [ 4,  5, 10],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 10]]])

In [81]:
np.sort(ar1[0],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  9],
       [ 7,  8, 10]])

In [82]:
np.sort(ar1[0],axis=1)

array([[ 1,  2,  3],
       [ 4,  5, 10],
       [ 7,  8,  9]])

In [89]:
n10 =np.array([2,3,1,5,10,12,6,9])
n10

array([ 2,  3,  1,  5, 10, 12,  6,  9])

In [92]:
n12=n10.reshape(2,4)
n12

array([[ 2,  3,  1,  5],
       [10, 12,  6,  9]])

In [93]:
n13 = np.arange(4)
n14=np.arange(5,9)
print(n13)
print(n14)

[0 1 2 3]
[5 6 7 8]


In [95]:
n15=np.concatenate((n13,n14))
n15

array([0, 1, 2, 3, 5, 6, 7, 8])

In [103]:
n16=np.arange(8) # 1d to 2d conversionn
n16
n17=n16[np.newaxis,:]
n17

array([[0, 1, 2, 3, 4, 5, 6, 7]])

In [102]:
n18=n16[:,np.newaxis]
n18

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [106]:
n19=np.expand_dims(n16,axis=1)
n19

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [107]:
n20=np.expand_dims(n16,axis=0)
n20

array([[0, 1, 2, 3, 4, 5, 6, 7]])

In [111]:
# conditional indexing
print (n12[n12%2==0])

[ 2 10 12  6]


In [112]:
print(np.sort(n12))

[[ 1  2  3  5]
 [ 6  9 10 12]]


In [113]:
# combining conditions
print(n12[(n12>3) &(n12<8)])

[5 6]


In [114]:
five=n12>5
print(five)

[[False False False False]
 [ True  True  True  True]]


In [115]:
print(n12[five])

[10 12  6  9]


In [122]:
print(np.nonzero(n12[0])) # index

(array([0, 1, 2, 3]),)


In [125]:
n12

array([[ 2,  3,  1,  5],
       [10, 12,  6,  9]])

In [126]:
 print(n12[0][2:4]) # slicing

[1 5]


In [129]:
# stacking 2d arrays
# horizontal and vertical stack
n22=np.array([[1,2],[3,4]])
n23=np.array([[5,6],[7,8]])
np.hstack((n22,n23))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [130]:
np.vstack((n22,n23))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [131]:
n24=np.arange(20)
n24

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [132]:
# split
# horizontal and vertical split
np.hsplit(n24,4)

[array([0, 1, 2, 3, 4]),
 array([5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14]),
 array([15, 16, 17, 18, 19])]

In [134]:
n12

array([[ 2,  3,  1,  5],
       [10, 12,  6,  9]])

In [143]:
n25=n24[:,np.newaxis]
n25

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [145]:
np.vsplit(n25,4)

[array([[0],
        [1],
        [2],
        [3],
        [4]]),
 array([[5],
        [6],
        [7],
        [8],
        [9]]),
 array([[10],
        [11],
        [12],
        [13],
        [14]]),
 array([[15],
        [16],
        [17],
        [18],
        [19]])]

In [146]:
# copy
n12

array([[ 2,  3,  1,  5],
       [10, 12,  6,  9]])

In [149]:
n12

array([[ 2,  3,  1,  5],
       [55, 55, 55, 55]])

In [151]:
n13=n12 # sha;low copy same array but with different names
n12[0][1]=10
n12

array([[ 2, 10,  1,  5],
       [55, 55, 55, 55]])

In [152]:
n13

array([[ 2, 10,  1,  5],
       [55, 55, 55, 55]])

In [160]:
n27=n24.copy() # deepcopy
# it creates a copu=y 

In [158]:
n24[1]=100
n24

array([  0, 100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [159]:
n27

array([ 0, 25,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [161]:
n27.sum()

np.int64(289)

In [162]:
n27.max()

np.int64(100)

In [163]:
n27.min()

np.int64(0)

In [164]:
n27*10

array([   0, 1000,   20,   30,   40,   50,   60,   70,   80,   90,  100,
        110,  120,  130,  140,  150,  160,  170,  180,  190])

In [165]:
np.random.rand(3,3)

array([[0.95368393, 0.06664873, 0.97124943],
       [0.82368093, 0.72716381, 0.51812818],
       [0.72709637, 0.20598907, 0.30464409]])

In [166]:
np.random.randint(20,size=(4,3))

array([[ 1, 11, 13],
       [ 4, 19,  0],
       [16,  6,  4],
       [17,  0, 13]], dtype=int32)

In [167]:
np.cos(n27)

array([ 1.        ,  0.86231887, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722,
       -0.75968791, -0.95765948, -0.27516334,  0.66031671,  0.98870462])