In [2]:
# Create a 1D NumPy array of numbers from 0 to 9.
import numpy as np

In [4]:
a=np.arange(0,9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
np.ndim(a)

1

In [7]:
# Create a 3×3 NumPy array with all elements as True.
b=np.full([3,3],True)
b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [17]:
#Create a 4×4 identity matrix.
c=np.eye(4,dtype='int')
c

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [19]:
# Generate a NumPy array of 5 random integers between 10 and 50.
d=np.random.randint(10,50,size=5)
d

array([36, 14, 22, 40, 47], dtype=int32)

In [22]:
#  Reshape a 1D array of size 9 into a 3×3 matrix.
e=np.arange(9)
np.size(e)
e

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
f=e.reshape(3,3)
f

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
#  Get the maximum and minimum values from a given NumPy array.
np.max(f)

np.int64(8)

In [26]:
np.min(f)

np.int64(0)

In [27]:
# Replace all even numbers in an array with -1.
f

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
f[f%2==0]=-1

In [30]:
f

array([[-1,  1, -1],
       [ 3, -1,  5],
       [-1,  7, -1]])

In [33]:
# Flatten a 2D array to 1D.
f.flatten()

array([-1,  1, -1,  3, -1,  5, -1,  7, -1])

In [34]:
# Find the mean, median, and standard deviation of a NumPy array.
f

array([[-1,  1, -1],
       [ 3, -1,  5],
       [-1,  7, -1]])

In [43]:
np.mean(f)

np.float64(1.2222222222222223)

In [44]:
np.median(f)

np.float64(-1.0)

In [45]:
np.std(f)

np.float64(2.897423291201177)

In [62]:
#  Check if any or all elements in a boolean array are True.
arr3=np.eye(3,dtype='int32')
bool_arr= arr3.astype(bool)
bool_arr

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [60]:
    import numpy as np

    int_arr = np.array([0, 10, -5, 0.0])
    bool_arr = int_arr.astype(bool)
    print(bool_arr)

[False  True  True False]
