In [14]:
#Write a program to reverse a string. Using function and loops 
def reve(a):
    rev=""
    for i in a:
        rev=i+rev
    return rev
b=input("Enter a string:")
print(f"The reverse of a string is {reve(b.lower())}")


Enter a string: SHaru


The reverse of a string is urahs


In [12]:
#Write a program to check if a string is a palindrome.
def palindrome(a):
    rev=""
    for i in a:
        rev=i+rev
    if rev==a:
        print("Palindrome")
    else:
        print("Not a palindrome")

a=input("Enter a string:")
palindrome(a.lower())

Enter a string: Madam


Palindrome


In [23]:
#Create a program to generate Fibonacci series up to n terms.
def fib(n):
    if n==0:
        return 0
    elif n==1 or n==2:
        return 1
    else:
        return fib(n-1) +fib(n-2)
a=[]
n= int(input("Enter a number:"))
for i in range (0, n+1):
    a.append(fib(i))
print(a)

Enter a number: 5


[0, 1, 1, 2, 3, 5]


In [62]:
# 4. Write a program to find all prime numbers up to n.
def prime(numbers):
    num=[]
    [num.append(i) for i in range (2,numbers+1) if all (i%j!=0 for j in range (2,i))]
    return num
numbers=int(input("Enter a number upto which you need prime :"))
print("Prime numbers are:",prime(numbers))


Enter a number upto which you need prime : 10


Prime numbers are: [2, 3, 5, 7]


In [65]:
# another method
def prime(numbers):
    num=[]
    for i in range (2,numbers+1):
        for j in range (2,i):
            if i%j==0:
                break
        else:
            num.append(i)
    return num
numbers=int(input("Enter a number upto which you need prime :"))
print("Prime numbers are:",prime(numbers))


Enter a number upto which you need prime : 10


Prime numbers are: [2, 3, 5, 7]


In [19]:
#  Write a program to remove duplicates from a list. Without set data structure
unique=[]
n=int(input("Enter the number of items you wanna add :"))
for i in range(0,n):
    item = input(f"Enter item number {i+1}:")
    if item not in unique:
        unique.append(item.lower())
print(f"The Groceries list is :{unique}")

Enter the number of items you wanna add : 6
Enter item number 1: sugar
Enter item number 2: sugar
Enter item number 3: coffe powder
Enter item number 4: milk
Enter item number 5: milk
Enter item number 6: chocolate


The Groceries list is :['sugar', 'coffe powder', 'milk', 'chocolate']


In [28]:
# 6. Create a program to find the second largest number in a list
nums=[]
n=int(input("Enter the number of numbers you want to enter :"))
[nums.append(int(input(f"Enter the number {i+1}")))for i in range (0,n)]
nums.sort()
print(nums[-2])

Enter the number of numbers you want to enter : 5
Enter the number 1 12
Enter the number 2 3
Enter the number 3 2
Enter the number 4 1
Enter the number 5 4


4


In [79]:
#7. Write a program to generate a simple calculator
def add(*args):
    total=sum(num for num in args)
    return total
def sub(a,b):
    dif=a-b
    return dif
def multi(*args):
    product=1
    for num in args:
        product=product*num
    return product
print(add(1,2,3,4))
print(sub(10,12))
print(multi(2,4,5,6))

10
-2
[2, 4, 5, 6]


In [22]:
# Create a 3D NumPy array of shape (2, 3, 4). Convert it into a 2D array and then flatten it into a 1D array.
import numpy as np
array1=np.array([
    [[1,2,3,4],[5,6,7,8],[9,10,11,12]],
    [[13,14,15,16],[17,18,19,20],[21,22,23,24]],

])
print(a1)

[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]


In [23]:
print(np.shape(array1))

(2, 3, 4)


In [27]:
a2d=array1.reshape([6,4])
a2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [28]:
a3d=a2d.flatten()
a3d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [35]:
"""
8. Write a program to read and write to files with error handling.
"""

'\n8. Write a program to read and write to files with error handling.\n'

In [33]:
# 10. Create two 2D NumPy arrays (3×2 and 2×3) and perform matrix multiplication using np.dot().
arr2 = np.array([[1,2],[4,5],[7,8]])
arr3=np.array([[11,12,13],[14,15,16]])
arr4=np.dot(arr2,arr3)
arr4

array([[ 39,  42,  45],
       [114, 123, 132],
       [189, 204, 219]])